import { useState, useEffect } from 'react';
import { supabase } from '../utils/supabase/client';
import { motion } from 'framer-motion';
import { Calendar, Clock, ArrowRight, BookOpen } from 'lucide-react';
import { log } from '../utils/logger';
import { SEOHead } from './SEOHead';

interface BlogListProps {
  onNavigate: (page: string, data?: any) => void;
}

export function BlogList({ onNavigate }: BlogListProps) {
  const [blogs, setBlogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // 👇 Page load hote hi Blogs fetch karo
  useEffect(() => {
    fetchBlogs();
  }, []);

  const fetchBlogs = async () => {
    setLoading(true);
    // Sirf published blogs dikhao, latest pehle
    const { data, error } = await supabase
      .from('blogs')
      .select('*')
      .eq('is_published', true)
      .order('created_at', { ascending: false });

    if (error) {
      log.error('Error fetching blogs:', error);
    } else {
      setBlogs(data || []);
    }
    setLoading(false);
  };

  // Helper to calculate reading time (approx)
  const getReadingTime = (content: string) => {
    const words = content.split(' ').length;
    return Math.ceil(words / 200) + ' min read';
  };

  // Helper to format date
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  };

  return (
    <>
      <SEOHead
        seo={{
          title: 'Tech Blog & AI Insights | NeuralCards',
          description:
            'Deep dives into AI, Machine Learning, Deep Learning and Software Engineering concepts. AI-generated articles curated for learners.',
          canonical: 'https://neural-cards.vercel.app/blog',
          schema: {
            '@context': 'https://schema.org',
            '@type': 'Blog',
            name: 'NeuralCards Tech Blog',
            description: 'Deep dives into AI, Machine Learning, and Software Engineering concepts.',
            url: 'https://neural-cards.vercel.app/blog',
            publisher: {
              '@type': 'Organization',
              name: 'NeuralCards',
              url: 'https://neural-cards.vercel.app',
            },
          },
        }}
      />
      <div className="min-h-screen bg-background pt-24 pb-20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl">
          {/* Header Section */}
          <motion.div
            className="text-center mb-16"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 mb-4 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-600 dark:text-blue-400 text-sm font-medium">
              <BookOpen className="w-4 h-4" />
              <span>Learning Resources</span>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-purple-600 dark:from-white dark:to-slate-400">
              Tech Blog & Insights
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Deep dives into AI, Machine Learning, and Software Engineering concepts. Generated by
              AI, Curated for You.
            </p>
          </motion.div>

          {/* Loading State */}
          {loading && (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              {[1, 2, 3].map((i) => (
                <div
                  key={i}
                  className="h-96 rounded-2xl bg-gray-100 dark:bg-zinc-900 animate-pulse"
                />
              ))}
            </div>
          )}

          {/* Content State */}
          {!loading && blogs.length === 0 ? (
            <div className="text-center py-20 bg-gray-50 dark:bg-zinc-900/50 rounded-2xl border border-dashed border-gray-300 dark:border-zinc-800">
              <h3 className="text-xl font-bold text-muted-foreground">No blogs published yet.</h3>
              <p className="text-sm text-gray-500">Go to Admin panel and generate some magic!</p>
            </div>
          ) : (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              {blogs.map((blog, index) => (
                <motion.div
                  key={blog.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className="group flex flex-col bg-card border border-border rounded-2xl overflow-hidden hover:shadow-2xl hover:shadow-purple-500/10 transition-all duration-300 cursor-pointer h-full"
                  onClick={() => onNavigate('blog-post', { slug: blog.slug })} // 👈 Action defined here
                >
                  {/* Image Placeholder or Real Image */}
                  <div className="h-48 bg-gradient-to-br from-gray-100 to-gray-200 dark:from-zinc-800 dark:to-zinc-900 flex items-center justify-center relative overflow-hidden">
                    {/* Abstract Shapes for visual appeal */}
                    <div className="absolute top-0 right-0 w-32 h-32 bg-purple-500/20 blur-[50px] rounded-full group-hover:bg-purple-500/30 transition-all" />
                    <BookOpen className="w-12 h-12 text-muted-foreground/30" />
                  </div>

                  <div className="p-6 flex-1 flex flex-col">
                    {/* Meta Data */}
                    <div className="flex items-center gap-4 text-xs text-muted-foreground mb-4 font-mono">
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3 h-3" /> {formatDate(blog.created_at)}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="w-3 h-3" /> {getReadingTime(blog.content)}
                      </span>
                    </div>

                    <h2 className="text-xl font-bold mb-3 line-clamp-2 group-hover:text-purple-600 dark:group-hover:text-purple-400 transition-colors">
                      {blog.title}
                    </h2>

                    {/* Markdown ka starting text dikhayenge (strip symbols manually or just show raw excerpt) */}
                    <p className="text-muted-foreground text-sm line-clamp-3 mb-6 flex-1">
                      {blog.content.replace(/[#*`]/g, '').slice(0, 150)}...
                    </p>

                    <div className="flex items-center justify-between pt-4 border-t border-border mt-auto">
                      <div className="flex items-center gap-2 text-xs font-bold text-muted-foreground">
                        <div className="w-6 h-6 rounded-full bg-gradient-to-tr from-blue-500 to-purple-500 flex items-center justify-center text-[10px] text-white">
                          AI
                        </div>
                        {blog.author || 'Vaibhav Kumar Mishra'}
                      </div>
                      <span className="text-sm font-bold text-purple-600 dark:text-purple-400 flex items-center gap-1 group-hover:translate-x-1 transition-transform">
                        Read Article <ArrowRight className="w-4 h-4" />
                      </span>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          )}
        </div>
      </div>
    </>
  );
}
